Feat/39
Rubminds/rubminds-frontend pull request #42
Opened 2021-12-30 06:31 UTC by colo1211

글생성 페이지 API saga 연동 완료, 

- 현재 사용자 입력 받는 스킬 셋은 임의로 입력해놓았음

2021-12-30 06:59 UTC, hanyoonseok requested changes

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
> +import { createPosts } from '../../../modules/post'
게시글 1개를 생성하는 것이기 때문에 단수형으로 변경하는게 좋을 것 같습니다 -> createPost

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
> +  const done  = useSelector((state)=>state.post.createpostDone);
네이밍 똑같이 맞춰주세요 -> createPostDone

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
> -      if (e.target.getAttribute('name') === 'recruitType') {
e.target.name으로 접근이 안되나요?

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
>              setBtnColor(['#FBEAFF', 'white', 'white'])
색을 상태변수로 갖지 말고 style.js에서 처리하도록 바꿔야할 거 같습니다.

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
> +      let data = {
새로 할당하는 부분이 없는 것 같은데, 이럴땐 const로 선언해주세요

2021-12-30 06:59 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
>    const onBodyChange = useCallback(
이 함수 역할이 너무 무겁습니다. radio는 radio끼리, 버튼은 버튼끼리 작동하도록 분리해야 할 듯 합니다

2021-12-30 06:59 UTC, hanyoonseok commented on src/modules/post/index.js
> +  createpostLoading : false,
->Post

2022-01-02 08:06 UTC, colo1211 commented on src/components/WritingPage/WrittingInnerForm/index.js
> +import { createPosts } from '../../../modules/post'
수정 완료

2022-01-02 08:09 UTC, colo1211 commented on src/components/WritingPage/WrittingInnerForm/index.js
> +  const done  = useSelector((state)=>state.post.createpostDone);
수정 완료

2022-01-02 08:13 UTC, colo1211 commented on src/components/WritingPage/WrittingInnerForm/index.js
> +      let data = {
수정 완료

2022-01-03 05:47 UTC, colo1211 commented on src/components/WritingPage/WrittingInnerForm/index.js
> -      if (e.target.getAttribute('name') === 'recruitType') {
넵 안되더라구요

2022-01-03 05:47 UTC, colo1211 commented on src/components/WritingPage/WrittingInnerForm/index.js
>    const onBodyChange = useCallback(
onBodyChange 함수 그냥 각각의 state로 빼서 각각의 컴포넌트에서 관리하도록 했습니다.

2022-01-03 05:48 UTC, colo1211 commented on src/modules/post/index.js
> +  createpostLoading : false,
수정 완료

2022-01-03 06:32 UTC, hanyoonseok commented on src/components/WritingPage/WrittingInnerForm/index.js
> +      let temp = result.data.skills
-> const

2022-01-03 06:45 UTC, hanyoonseok commented on src/modules/user/index.js
> +  data: data,
data, 로 단축가능

2022-01-03 06:48 UTC, hanyoonseok commented on src/components/WritingPage/Content/index.js
> +const Content = ({content, setContent}) => {
컴포넌트 명을 직관적으로 작성해주세요.
content x 
어떤 컨텐츠인지 혹은 무엇에 관한 컨텐츠인지.
ex) recruitContent, postContent, projectContent

2022-01-03 06:56 UTC, hanyoonseok approved these changes
코멘트 남긴건 다음 pr 때 수정해서 올려주세요.

2022-01-03 06:56 UTC, merged