Feat/47
Rubminds/rubminds-frontend pull request #52
Opened 2022-01-07 12:31 UTC by colo1211

- 회원가입 중복체크 API 연결
- 로그인 파일 없을 때하고 있을 때 분기처리 (LoginProcess)
- 글 생성 페이지 접속 안되는 것 수정

2022-01-07 15:28 UTC, hanyoonseok commented on src/components/SignUp/SignUpPageRight/index.js
> +  const nicknameCheckHandler = useCallback(()=>{
useCallback(async()=>{
...
},[])
으로 단축할 수 있을 것 같아요

2022-01-07 15:35 UTC, hanyoonseok commented on src/pages/DibsPage/index.js
> +  const [apiQuery, setApiQuery] = useState('/api/posts/like?page=1&size=10');
api를 왜 붙이셨나요? 저대로 보내면 아마 에러 날거에요

2022-01-07 15:35 UTC, hanyoonseok commented on src/components/SignUp/NickName/index.js
> +        `api/user/nickname/check?nickname=${nickname}`,
마찬가지로 `api` 빼주세요

2022-01-07 15:36 UTC, hanyoonseok commented on src/modules/post/saga.js
> +  return axios.post('/api/post', data , {
api 제거

2022-01-07 15:37 UTC, hanyoonseok requested changes
코멘트 읽어주시고 수정 후에 승인해드리겠습니다~

2022-01-08 06:30 UTC, colo1211 commented on src/pages/DibsPage/index.js
> +  const [apiQuery, setApiQuery] = useState('/api/posts/like?page=1&size=10');
수정 완료했습니다.

2022-01-08 06:31 UTC, colo1211 commented on src/modules/post/saga.js
> +  return axios.post('/api/post', data , {
수정 완료

2022-01-08 06:32 UTC, colo1211 commented on src/components/SignUp/NickName/index.js
> +        `api/user/nickname/check?nickname=${nickname}`,
수정 완료

2022-01-09 05:52 UTC, hanyoonseok approved these changes

2022-01-09 05:52 UTC, merged