Feat/64
Rubminds/rubminds-frontend pull request #66
Opened 2022-01-20 05:28 UTC by colo1211

2022-01-20 10:49 UTC, hanyoonseok commented on src/pages/EditPostPage/index.js
>  import Content from '../../components/EditPost/Content';
import url을 한번에 받아올 수 있게 '../../' 로 해주세요

2022-01-20 10:58 UTC, hanyoonseok commented on src/pages/EditPostPage/index.js
>    const { singlePost } = useSelector(state => state.post);
아마 비동기 처리때문에 saga말고 axios 써야 할거에요

2022-01-20 11:09 UTC, hanyoonseok requested changes
- 게시글 수정할 때 지역 데이터 수정해도 반영이 안되네요
- 현재 참여한 팀원 수 보다 모집인원 작게 설정 못하게 막아야 할 거 같습니다
- 페이지에 워닝메시지 제거해주세요
- 유저프로필 수정시 프로필 이미지가 안옵니다
- 유저 프로필이미지 크기 고정 필요
- 유저 프로필 수정시 redirect 하는 주소 변경(mypage->userpage)
- 유저프로필 수정 500에러

2022-01-21 07:34 UTC, colo1211 commented on src/pages/EditPostPage/index.js
>  import Content from '../../components/EditPost/Content';
알겠습니다

2022-01-21 07:35 UTC, colo1211 commented on src/pages/EditPostPage/index.js
>    const { singlePost } = useSelector(state => state.post);
알겠습니다 진짜 62 branch 에서 죄다 에러나네요

2022-01-26 11:08 UTC, hanyoonseok approved these changes

2022-01-26 11:08 UTC, merged